# Generated by Django 5.2.1 on 2025-05-29 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('medical_doc', models.FileField(upload_to='applications/')),
                ('bank_receipt', models.FileField(upload_to='applications/')),
                ('application', models.FileField(upload_to='applications/')),
                ('student_card', models.FileField(upload_to='applications/')),
                ('application_partion_pay', models.FileField(upload_to='applications/')),
                ('aplication_parent_pay', models.FileField(upload_to='applications/')),
                ('contract', models.FileField(upload_to='applications/')),
                ('personal_account', models.FileField(upload_to='applications/')),
                ('comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('approved', 'Принята'), ('rejected', 'Отклонена')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('floor', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('capacity', models.IntegerField()),
                ('about', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='room_images/')),
                ('residents', models.ManyToManyField(blank=True, related_name='shared_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
