# Generated by Django 5.2.1 on 2025-05-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(default='room_images/default.jpg', upload_to='room_images/'),
        ),
    ]
