# Generated by Django 5.2.1 on 2025-06-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='news_images/default.png', upload_to='news_images/', verbose_name='Зображення'),
        ),
    ]
