# Generated by Django 5.2.1 on 2025-05-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='about',
            field=models.TextField(default='Звичайна кімната'),
        ),
    ]
