# Generated by Django 5.2.1 on 2025-06-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='aplication_parent_pay',
            field=models.FileField(blank=True, upload_to='applications/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='application_partion_pay',
            field=models.FileField(blank=True, upload_to='applications/'),
        ),
    ]
